CREATE TABLE IF NOT EXISTS `EmployeeWorkReports` (
  `Id` INT(10) NOT NULL AUTO_INCREMENT,
  `userId` INT(10) NOT NULL,
  `employeeId` INT(10) NULL,
  `reportDate` DATE NOT NULL,
  `name` VARCHAR(180) NOT NULL,
  `failedGiven` INT(10) NOT NULL DEFAULT 0,
  `failedReceived` INT(10) NOT NULL DEFAULT 0,
  `pendingGiven` INT(10) NOT NULL DEFAULT 0,
  `pendingReceived` INT(10) NOT NULL DEFAULT 0,
  `pendingReturnReceived` INT(10) NOT NULL DEFAULT 0,
  `canceledReceived` INT(10) NOT NULL DEFAULT 0,
  `holdReceived` INT(10) NOT NULL DEFAULT 0,
  `ideskGiven` INT(10) NOT NULL DEFAULT 0,
  `ideskReceived` INT(10) NOT NULL DEFAULT 0,
  `callDone` INT(10) NOT NULL DEFAULT 0,
  `callReceived` INT(10) NOT NULL DEFAULT 0,
  `whatsappDone` INT(10) NOT NULL DEFAULT 0,
  `whatsappReceived` INT(10) NOT NULL DEFAULT 0,
  `totalAssign` INT(10) NOT NULL DEFAULT 0,
  `totalOrder` INT(10) NOT NULL DEFAULT 0,
  `totalAmount` DECIMAL(15, 2) NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `deletedAt` DATETIME NULL,
  PRIMARY KEY (`Id`),
  UNIQUE KEY `uniq_employee_work_report_user_date` (`userId`, `reportDate`),
  INDEX `idx_employee_work_reports_report_date` (`reportDate`),
  INDEX `idx_employee_work_reports_employee` (`employeeId`),
  INDEX `idx_employee_work_reports_deleted_at` (`deletedAt`)
);
