const MENU_PERMISSIONS = {
  OVERVIEW: "overview",
  USER_MANAGEMENT: "user_management",
  ASSETS: "assets",
  ASSETS_STOCK: "assets_stock",
  REQUISITION: "requisition",
  PURCHASE: "purchase",
  SALE: "sale",
  DAMAGE: "damage",
  MARKETING: "marketing",
  DM_EXPENSE: "dm_expense",
  PROFIT_LOSS: "profit_loss",
  MANUFACTURE: "manufacture",
  ITEM: "item",
  MANUFACTURE_STOCK: "manufacture_stock",
  MANUFACTURE_MENU: "manufacture_menu",
  STOCK_ADJUSTMENT: "stock_adjustment",
  MIXER: "mixer",
  INVENTORY: "inventory",
  INVENTORY_OVERVIEW: "inventory_overview",
  STOCK_PRODUCT: "stock_product",
  WAREHOUSE: "warehouse",
  SUPPLIER: "supplier",
  PRODUCT: "product",
  PURCHASE_REQUISITION: "purchase_requisition",
  RECEIVED_PRODUCT: "received_product",
  RECEIVED_RETURN: "received_return",
  INTRANSIT_PRODUCT: "intransit_product",
  SALES_RETURN: "sales_return",
  DAMAGE_MANAGEMENT: "damage_management",
  DAMAGE_STOCK: "damage_stock",
  DAMAGE_PRODUCT: "damage_product",
  DAMAGE_REPAIRING_STOCK: "damage_repairing_stock",
  DAMAGE_REPAIRING: "damage_repairing",
  DAMAGE_REPAIRED: "damage_repaired",
  POS_PANEL: "pos_panel",
  SELL: "sell",
  POS_REPORT: "pos_report",
  ACCOUNTING: "accounting",
  ACCOUNTING_SUPPLIER: "accounting_supplier",
  BOOK: "book",
  PETTY_CASH_REQUISITION: "petty_cash_requisition",
  PETTY_CASH: "petty_cash",
  CREDIT_LEDGER: "credit_ledger",
  NOTIFICATIONS: "notifications",
  SETTINGS: "settings",
  LOGO: "logo",
  ROLE_PERMISSIONS: "role_permissions",
  HRM: "hrm",
  EMPLOYEE_MANAGEMENT: "employee_management",
  DEPARTMENT_DESIGNATION: "department_designation",
  SHIFT_MANAGEMENT: "shift_management",
  HOLIDAY_MANAGEMENT: "holiday_management",
  ATTENDANCE: "attendance",
  ATTENDANCE_DEVICE: "attendance_device",
  LEAVE_MANAGEMENT: "leave_management",
  PAYROLL_MANAGEMENT: "payroll_management",
  PAYSLIP: "payslip",
  EMPLOYEE_PROFILE: "employee_profile",
  HR_PAYROLL: "hr_payroll",
  EMPLOYEE_LIST: "employee_list",
  PAYROLL: "payroll",
  PAYROLL_FINE: "payroll_fine",
  EXPIRED_PRODUCT: "expired_product",
  PROFILE: "profile",
};

const ALL_MENU_PERMISSIONS = Object.values(MENU_PERMISSIONS);

module.exports = {
  MENU_PERMISSIONS,
  ALL_MENU_PERMISSIONS,
};
